export const GET_TASKS_REQUEST = "GET_TASKS_REQUEST";
export const GET_TASKS_COMPLETE = "GET_TASKS_COMPLETE";
export const ADD_NEW_TASK_REQUEST = "ADD_NEW_TASK_REQUEST";
export const ADD_NEW_TASK_COMPLETE = "ADD_NEW_TASK_COMPLETE";
export const COMPLETE_TASK_REQUEST = "COMPLETE_TASK_REQUEST";
export const COMPLETE_TASK_COMPLETE = "COMPLETE_TASK_COMPLETE";
export const REMOVE_TASK_REQUEST = "REMOVE_TASK_REQUEST";
export const REMOVE_TASK_COMPLETE = "REMOVE_TASK_COMPLETE";

export const SET_TASKS_FILTER = "SET_TASKS_FILTER";

export const SET_SELECTED_TASK_ID = "SET_SELECTED_TASK_ID";